import { test,expect,type Page } from "@playwright/test";
async function login(page:Page,roll:string,code:string){await page.goto("/login");await page.locator('input[name="rollNumber"]').fill(roll);await page.locator('input[name="classCode"]').fill(code);await page.getByRole("button",{name:"Authenticate"}).click();await page.waitForURL(url=>!url.pathname.startsWith("/login"))}
test.describe.serial("competition intelligence flow",()=>{
 test("student receives an actual stored ClassGuard citation",async({page})=>{await login(page,"07","student123");await page.goto("/assistant");await page.locator('textarea[name="message"]').fill("Is washroom payment required?");await page.getByRole("button",{name:"Ask ClassGuard"}).click();await expect(page.getByText("Stored school rules",{exact:true}).last()).toBeVisible();await expect(page.getByText("grounded",{exact:true}).last()).toBeVisible()});
 test("TruthLens returns a non-absolute contradiction with evidence",async({page})=>{await login(page,"12","student123");await page.goto("/truthlens");await page.locator('textarea[name="claim"]').fill("Students are required to pay a fee to use the washroom.");await page.getByRole("button",{name:"Run grounded check"}).click();await expect(page.getByText("MISLEADING",{exact:true})).toBeVisible();await expect(page.getByText("Free washroom access",{exact:true})).toBeVisible()});
 test("teacher behaviour dashboard shows hotspot and limitation",async({page})=>{await login(page,"T01","teacher123");await page.goto("/teacher/behaviour-intelligence");await expect(page.getByText("Corridor",{exact:true})).toBeVisible();await expect(page.getByText("not a psychological assessment",{exact:false})).toBeVisible()});
 test("one anonymous proposal vote is accepted and a duplicate rejected",async({page})=>{await login(page,"07","student123");await page.goto("/democracy/proposals/PROP-DEMO-OPEN");await page.getByRole("button",{name:"support"}).click();await page.getByRole("button",{name:"support"}).click();await expect(page.getByText("One vote per eligible student is allowed")).toBeVisible()});
 test("teacher can unlock an eligible impeachment vote",async({page})=>{await login(page,"T01","teacher123");await page.goto("/teacher/democracy");await page.getByRole("button",{name:"Open eligible impeachment vote"}).click();await expect(page.getByText(/Impeachment vote opened|already active/i)).toBeVisible()});
});
