import { deterministicEmbedding } from "@/services/embedding.service";import { cosineSimilarity } from "@/algorithms/core";import { SchoolRule } from "@/models/SchoolRule";import { OfficialNotice } from "@/models/OfficialNotice";import { TruthLensResponseSchema } from "./truthlens.schema";
export async function checkClaim(claim:string,technicalIndicators:any=null){
 const normalized=claim.replace(/\s+/g," ").trim();
 const [rules,notices]=await Promise.all([SchoolRule.find({active:true}).lean(),OfficialNotice.find({active:true}).lean()]) as unknown as [any[],any[]];
 const q=deterministicEmbedding(normalized);const sources=[...rules.map(x=>({id:x._id,title:x.title,text:x.exactText,type:"school_rule",section:x.section,page:x.sourcePage})),...notices.map(x=>({id:x._id,title:x.title,text:x.body,type:"official_notice",section:x.noticeType,page:null}))].map(x=>({...x,score:cosineSimilarity(q,deterministicEmbedding(`${x.title} ${x.text}`))})).sort((a,b)=>b.score-a.score).slice(0,5);
 if(!sources.length||sources[0].score<.1)return TruthLensResponseSchema.parse({status:"INSUFFICIENT_EVIDENCE",heuristicEvidenceConfidence:0,claim:normalized,explanation:"No sufficiently relevant official stored source was found.",reasons:["Official context is insufficient."],evidence:[],recommendedAction:"Ask a teacher to publish or clarify the official notice.",technicalIndicators});
 const top=sources[0],directContradiction=(/\b(pay|payment|fee|required)\b/i.test(normalized)&&/\b(free|without (?:pay|payment|fee)|no (?:pay|payment|fee))\b/i.test(top.text))||(/\bcancel(?:led|lation)?\b/i.test(normalized)&&/\b(no|not)\s+cancel/i.test(top.text)),claimNegated=/\b(no|not|never)\b/i.test(normalized),sourceNegated=/\b(no|not|never|without|free|may not)\b/i.test(top.text),contradiction=directContradiction||claimNegated!==sourceNegated,status=contradiction?"MISLEADING":top.score>.35?"LIKELY_SUPPORTED":"UNVERIFIED";
 return TruthLensResponseSchema.parse({status,heuristicEvidenceConfidence:Math.round(Math.min(95,35+top.score*60)),claim:normalized,explanation:contradiction?"The claim conflicts with the closest official stored source.":"The claim has related official evidence, but this does not prove authenticity.",reasons:[contradiction?"Contradiction detected against stored official wording.":"Relevant official wording was found."],evidence:sources.map(x=>({sourceTitle:x.title,sourceType:x.type,section:x.section??null,pageNumber:x.page??null,relevanceScore:Number(x.score.toFixed(3))})),recommendedAction:"Confirm the current notice with the named school authority before acting.",technicalIndicators});
}
