// @ts-nocheck -- seed values are controlled and idempotently upserted.
import mongoose from "mongoose";import bcrypt from "bcryptjs";import { createHmac } from "crypto";import dotenv from "dotenv";dotenv.config({path:".env.local"});
import { User } from "../src/models/User";import { StudentProfile } from "../src/models/StudentProfile";import { SchoolRule } from "../src/models/SchoolRule";import { FoodItem } from "../src/models/FoodItem";import { AppSetting } from "../src/models/AppSetting";import { Complaint } from "../src/models/Complaint";import { startCompetitionDemo } from "../src/services/demo/competition-demo.service";
const uri=process.env.MONGODB_URI,dbName=process.env.MONGODB_DB_NAME||"anti_kuddus_protocol",secret=process.env.ROLL_LOOKUP_SECRET;if(!uri||!secret)throw new Error("MONGODB_URI and ROLL_LOOKUP_SECRET are required in .env.local.");const hash=(roll:string)=>createHmac("sha256",secret).update(roll.trim().toUpperCase().replace(/\s+/g,"")).digest("hex");
async function run(){
 await mongoose.connect(uri,{dbName});
 const users=[{roll:"07",name:"Student 07",code:"student123",role:"student"},{roll:"12",name:"Student 12",code:"student123",role:"student"},{roll:"02",name:"Captain Biltu",code:"captain123",role:"captain",captainRank:2},{roll:"03",name:"Captain Miltu",code:"captain123",role:"captain",captainRank:3},{roll:"T01",name:"Rashid Sir",code:"teacher123",role:"teacher"},{roll:"A01",name:"Administrator",code:"admin123",role:"admin"}];
 for(const u of users)await User.updateOne({rollLookupHash:hash(u.roll)},{$set:{name:u.name,secretHash:await bcrypt.hash(u.code,12),role:u.role,captainRank:u.captainRank,active:true}},{upsert:true});
 const names=["Arafat","Borna","Chayan","Dipa","Emon","Farha","Gazi","Hira","Imran","Jannat","Kuddus","Lamia","Mahin","Nadia","Ovi","Priya","Rafi","Sadia","Tanvir","Urmi"];
 for(let i=0;i<names.length;i++)await StudentProfile.updateOne({rollNumber:String(i+1).padStart(2,"0")},{$set:{name:names[i],heightCm:140+(i*7)%34,visionImpairment:i===3,hearingImpairment:i===8,accessibilityRequirement:i===3?"Front row for board visibility":undefined,fixedSeat:i===1?{row:1,column:1}:undefined,isKuddus:names[i]==="Kuddus"}},{upsert:true});
 const rules=[["SR-001","Homework applies to captains","Academic duties","Class captains must submit homework under the same deadlines as all students."],["SR-002","Free washroom access","Student welfare","Students may use the washroom without paying any fee or bribe."],["SR-003","Test approval","Assessment","Class tests require prior approval from the assigned subject teacher."],["SR-004","Captain consultation","Student leadership","Captains must consult the other class captains before making a major class decision."],["SR-005","Food consent","Personal property","Food may not be taken from a student without that student's consent."],["SR-006","Fair seating","Classroom conduct","Seat assignments must account for vision, hearing, accessibility, and classroom safety."],["SR-007","Sports access","Extracurricular activities","Students may participate in scheduled sports unless a teacher documents a safety restriction."],["SR-008","No collective punishment","Discipline","A whole class may not be punished for conduct attributed to an unidentified individual."],["SR-009","Syllabus source","Academic duties","Test syllabi must be based on the approved curriculum and announced official materials."],["SR-010","Complaint privacy","Student welfare","A student making a good-faith complaint is entitled to protection from retaliation."],["SR-011","Emergency response","Safety","Class captains must promptly relay a student safety alert to a responsible teacher."],["SR-012","Evidence review","Discipline","A disciplinary finding must be based on reviewed evidence and an opportunity to respond."]];
 for(const [ruleId,title,section,exactText] of rules)await SchoolRule.updateOne({ruleId},{$set:{title,section,exactText,embedding:[],active:true}},{upsert:true});
 for(const [name,unit,cal] of [["Fried rice","plate",520],["Sandwich","piece",280],["Samosa","piece",260],["Singara","piece",230],["Cake","slice",310],["Premium jhalmuri","bowl",360]])await FoodItem.updateOne({name},{$set:{unit,estimatedCaloriesPerUnit:cal,active:true}},{upsert:true});
 for(const [key,value] of [["impeachment_threshold",3],["impeachment_minimum_turnout",60],["impeachment_required_support",66],["impeachment_voting_hours",24],["cricket_bat_demo_price",3500],["premium_jhalmuri_demo_price",120]])await AppSetting.updateOne({key},{$set:{value}},{upsert:true});
 const base=[{publicId:"DEMO-VERIFIED-01",category:"washroom_bribe",description:"A payment was demanded before washroom access during the break period.",incidentDate:new Date(Date.now()-5*86400000),location:"Classroom corridor",status:"verified"},{publicId:"DEMO-VERIFIED-02",category:"tiffin_theft",description:"Food was taken from a lunch box without the student's consent.",incidentDate:new Date(Date.now()-3*86400000),location:"Classroom",status:"verified"},{publicId:"DEMO-PENDING-01",category:"syllabus_bloat",description:"Several topics outside the announced curriculum were added to the test list.",incidentDate:new Date(),location:"Classroom",status:"pending"},{publicId:"DEMO-REJECTED-01",category:"other",description:"A report was submitted without enough verifiable incident detail for review.",incidentDate:new Date(Date.now()-9*86400000),location:"Playground",status:"rejected",reviewReason:"Insufficient evidence"}];
 for(const item of base)await Complaint.updateOne({publicId:item.publicId},{$set:item},{upsert:true});
 const admin=await User.findOne({role:"admin"});await startCompetitionDemo(String(admin._id));
 console.log("Seed complete: original six missions plus ClassGuard, TruthLens, behaviour intelligence, democracy, and labelled competition demo data.");await mongoose.disconnect();
}
run().catch(async e=>{console.error(e);await mongoose.disconnect();process.exit(1)});
